name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  zap_scan:
    name: Scan ZAP website
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker Version
        run: docker --version

      - name: Run ZAP Baseline Scan
        id: zap_scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://www.zaproxy.org/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save ZAP Scan Results
        run: |
          cat results.json
        continue-on-error: true
      
      - name: Analyze ZAP Results
        id: analyze
        run: |
          echo "Checking for high severity vulnerabilities..."
          jq -r '.site[].alerts[] | select(.risk == "High")' results.json > high_severity_alerts.json
          if [[ -s high_severity_alerts.json ]]; then
            echo "High severity vulnerabilities found!"
            exit 1
          else
            echo "No high severity vulnerabilities found."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
