name: ZAP Scan

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.10.0  # Update to the latest version
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target: 'http://localhost:5000'
        rules_file: '.github/zap_rules.tsv'
