name: Build and Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  setup-network:
    name: Setup Docker Network
    runs-on: ubuntu-latest
    steps:
      - name: Create Docker Network
        run: docker network create my-network

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: setup-network
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u med2205 --password-stdin

      - name: Build Docker image
        run: docker build -t my-flask-app -f ./secops/dockerfile .

      - name: Delay for Network Creation
        run: sleep 30

      - name: Run Docker container
        run: docker run -d -p 5000:5000 --network my-network my-flask-app

  zap_scan:
    name: Scan with ZAP
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare Workspace and Reports
        run: |
          mkdir -p $GITHUB_WORKSPACE/zap
          chmod -R a+w $GITHUB_WORKSPACE/zap

      - name: Run ZAP Baseline Scan
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable -q
          docker run -v $GITHUB_WORKSPACE/zap:/zap/wrk/:rw --network my-network -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://my-flask-app:5000/ -J /zap/wrk/report_json.json -w /zap/wrk/report_md.md -r /zap/wrk/report_html.html

      - name: Analyze ZAP Results
        run: |
          echo "Checking for high severity vulnerabilities..."
          jq -r '.site[].alerts[] | select(.risk == "High")' $GITHUB_WORKSPACE/zap/report_json.json > $GITHUB_WORKSPACE/zap/high_se
