name: Security and Quality Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  stackhawk:
    name: StackHawk
    runs-on: ubuntu-20.04
    permissions:
      contents: read  # for actions/checkout to fetch code
      security-events: write  # for stackhawk/hawkscan-action to upload code scanning alert info
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files in the repository
        run: ls -al

      - name: Ensure Dockerfile exists
        run: |
          if [ ! -f ./Dockerfile ]; then
            echo "Dockerfile not found!"
            exit 1
          fi

      - name: Ensure docker-compose.yml exists
        run: |
          if [ ! -f ./docker-compose.yml ]; then
            echo "docker-compose.yml not found!"
            exit 1
          fi

      - name: Start your service
        run: docker-compose up --build --detach

      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@4c3258cd62248dac6d9fe91dd8d45928c697dee0
        continue-on-error: true  # Set to false to break your build on scan errors
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          codeScanningAlerts: true
          githubToken: ${{ github.token }}
