name: Security and Quality Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  stackhawk:
    name: StackHawk
    runs-on: ubuntu-20.04
    permissions:
      contents: read  # for actions/checkout to fetch code
      security-events: write  # for stackhawk/hawkscan-action to upload code scanning alert info
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Uncomment and update the following step to start your service
      - name: Start your service
        run: docker-compose up --build --detach

      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@4c3258cd62248dac6d9fe91dd8d45928c697dee0
        continue-on-error: true  # Set to false to break your build on scan errors
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          codeScanningAlerts: true
          githubToken: ${{ github.token }}
